#

pluginName = fr.n7.idm.layout Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Layout_type = Layout
_UI_Board_type = Board
_UI_Couche_type = Couche
_UI_Coucheexterne_type = Coucheexterne
_UI_Coucheinterne_type = Coucheinterne
_UI_ComposantPlace_type = Composant Place
_UI_Piste_type = Piste
_UI_Point_type = Point
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Layout_name_feature = Name
_UI_Layout_description_feature = Description
_UI_Layout_boards_feature = Boards
_UI_Layout_netlist_feature = Netlist
_UI_Board_name_feature = Name
_UI_Board_largeur_feature = Largeur
_UI_Board_hauteur_feature = Hauteur
_UI_Board_couches_feature = Couches
_UI_Couche_name_feature = Name
_UI_Couche_numero_feature = Numero
_UI_Couche_pistes_feature = Pistes
_UI_Coucheexterne_composantPlaces_feature = Composant Places
_UI_ComposantPlace_x_feature = X
_UI_ComposantPlace_y_feature = Y
_UI_ComposantPlace_rotation_feature = Rotation
_UI_ComposantPlace_instance_feature = Instance
_UI_Piste_largeur_feature = Largeur
_UI_Piste_net_feature = Net
_UI_Piste_points_feature = Points
_UI_Point_x_feature = X
_UI_Point_y_feature = Y
_UI_Unknown_feature = Unspecified

