#

pluginName = fr.n7.idm.catalog Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Catalogue_type = Catalogue
_UI_Composant_type = Composant
_UI_Metadonnee_type = Metadonnee
_UI_Empreinte_type = Empreinte
_UI_Port_type = Port
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Catalogue_name_feature = Name
_UI_Catalogue_composants_feature = Composants
_UI_Composant_name_feature = Name
_UI_Composant_fabricant_feature = Fabricant
_UI_Composant_metadonnees_feature = Metadonnees
_UI_Composant_empreinte_feature = Empreinte
_UI_Composant_ports_feature = Ports
_UI_Composant_id_feature = Id
_UI_Metadonnee_cle_feature = Cle
_UI_Metadonnee_valeur_feature = Valeur
_UI_Metadonnee_type_feature = Type
_UI_Empreinte_largeur_feature = Largeur
_UI_Empreinte_hauteur_feature = Hauteur
_UI_Empreinte_forme_feature = Forme
_UI_Port_name_feature = Name
_UI_Port_x_feature = X
_UI_Port_y_feature = Y
_UI_Port_type_feature = Type
_UI_Unknown_feature = Unspecified

_UI_FormeFigure_RECTANGLE_literal = RECTANGLE
_UI_FormeFigure_CERCLE_literal = CERCLE
_UI_FormeFigure_PERSONNALISE_literal = PERSONNALISE
_UI_TypePort_ENTREE_literal = ENTREE
_UI_TypePort_SORTIE_literal = SORTIE
_UI_TypePort_BIDIRECTIONNEL_literal = BIDIRECTIONNEL
_UI_TypePort_ALIMENTATION_literal = ALIMENTATION
_UI_TypePort_MASSE_literal = MASSE
_UI_TypePort_NON_CONNECTE_literal = NON_CONNECTE
_UI_TypeMetadonnee_TEXTE_literal = TEXTE
_UI_TypeMetadonnee_NOMBRE_literal = NOMBRE
_UI_TypeMetadonnee_BOOLEEN_literal = BOOLEEN
